name: Pharo Unit Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk:
          - Pharo64-10
          - Pharo64-11
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Start memcached
        run: docker run -d -p 127.0.0.1:11211:11211 memcached:1.6.7-alpine
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: Unit-Tests-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
